language: node_js
node_js:
  - '10'
script: npm run build
deploy:
  local-dir: _site
  provider: pages
  skip-cleanup: true
  target-branch: master
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: develop
